perf: limit sa name
kubernetes-sigs/alibaba-cloud-csi-driver pull request #1096
Opened 2024-06-25 12:22 UTC by AlbeeSo

#### What type of PR is this?

#### What this PR does / why we need it:

#### Which issue(s) this PR fixes:

Fixes #

#### Special notes for your reviewer:

#### Does this PR introduce a user-facing change?

```release-note

```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

2024-06-25 13:23 UTC, huww98 requested changes

2024-06-25 13:23 UTC, huww98 commented on pkg/mounter/fuse_containerized_mounter.go
>  		if mounter.authCfg.RrsaConfig.ServiceAccountName == fuseServieAccountName {
```suggestion
		if mounter.authCfg.RrsaConfig.ServiceAccountName == fuseServiceAccountName {
```

2024-06-26 02:13 UTC, AlbeeSo commented on pkg/mounter/fuse_containerized_mounter.go
> +	if !strings.HasPrefix(name, "csi-fuse-") {
it is a shared mounter for all kinds of fuse. it is necessary to check the fuse daemon type first (ossfs, efc ..) then the serviceaccount name ?

2024-06-26 03:12 UTC, AlbeeSo commented on pkg/mounter/fuse_containerized_mounter.go
>  		if mounter.authCfg.RrsaConfig.ServiceAccountName == fuseServieAccountName {
default sa exists check has removed.

2024-06-26 03:15 UTC, AlbeeSo commented on pkg/mounter/fuse_containerized_mounter.go
> +	if !strings.HasPrefix(name, "csi-fuse-") {
will csi-fuse be better as I expect all the default sa name will be csi-fuse-ossfs, csi-fuse-efc ...
and here we can only check if sa starts with csi-fuse- whatever the fuse daemon type. 
(this func is for a common fuse mounter)

2024-06-26 03:19 UTC, huww98 commented on pkg/mounter/fuse_containerized_mounter.go
> +		return fmt.Errorf("service account name %s must start with csi-fuse-", name)
```suggestion
		return fmt.Errorf("service account name %s must start with %s", name, fuseServiceAccountNameValidPrefix)
```

2024-06-26 03:24 UTC, huww98 commented on pkg/mounter/fuse_containerized_mounter.go
> +	if !strings.HasPrefix(name, "csi-fuse-") {
OK, since you removed the default SA check. I was thinking about doing the check in `checkRRSAParams`, which is specific to ossfs.

2024-10-15 05:53 UTC, closed without merging