feat: change unit of node_volume_capacity_bytes_* to bytes (nas)
kubernetes-sigs/alibaba-cloud-csi-driver pull request #1120
Opened 2024-08-02 02:49 UTC by iltyty

#### What type of PR is this?
/kind feature

#### What this PR does / why we need it:
Change unit of node_volume_capacity_bytes_total, node_volume_capacity_bytes_used, node_volume_capacity_bytes_available to bytes (nas).

#### Which issue(s) this PR fixes:

Fixes #

#### Special notes for your reviewer:

#### Does this PR introduce a user-facing change?

```release-note

```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

2024-08-02 04:59 UTC, huww98 requested changes

2024-08-02 04:59 UTC, huww98 commented on pkg/metric/nfs_stat_collector.go
> +		total, used = info.TotalSize, info.UsedSizeInBytes
```suggestion
	if info.UsedSizeInBytes != 0 {
		total, used = info.TotalSizeInBytes, info.UsedSizeInBytes
```
Maybe we don't need the isNewVersion parameter?
We may not change the meaning of existing field, or we will break users that does not upgrade CSI.

2024-08-02 05:08 UTC, huww98 requested changes
We should also change the error message in capacityEventAlert

2024-08-02 09:04 UTC, huww98 approved these changes
/lgtm
/assign @mowangdk
for approval
/ok-to-test

2024-08-30 02:38 UTC, mowangdk commented
@iltyty Does this PR have any user-facing changes or impact users?

2024-08-30 02:46 UTC, tydra-wang commented
@iltyty Maybe you should rename the title to "Support byte-level NAS capacity metrics". It does not actually change the **unit** of the metrics.

2024-08-30 03:37 UTC, iltyty commented
> @iltyty Maybe you should rename the title to "Support byte-level NAS capacity metrics". It does not actually change the **unit** of the metrics.

done

2024-08-30 03:39 UTC, iltyty commented
> @iltyty Does this PR have any user-facing changes or impact users?

nope

2024-08-30 06:18 UTC, mowangdk commented
/lgtm
/approve

2024-08-30 06:25 UTC, merged