Upgrade cluster tag key for new created disk and snapshot
kubernetes-sigs/alibaba-cloud-csi-driver pull request #1122
Opened 2024-08-02 10:17 UTC by mowangdk

#### What type of PR is this?

/kind api-change
/kind cleanup

#### What this PR does / why we need it:
csi-provisioner now supports multiple types CO, rendering the "ack" tag name unsuitable for identifying resources it creates.

#### Which issue(s) this PR fixes:

Fixes #
None

#### Special notes for your reviewer:

#### Does this PR introduce a user-facing change?

```release-note

```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

2024-08-02 10:20 UTC, mowangdk commented
/assign AlbeeSo

2024-08-02 10:26 UTC, huww98 requested changes
So, this is a breaking change. Maybe we should keep both for half a year or so? To let the clients upgrade their scripts.

2024-08-02 10:26 UTC, huww98 commented on pkg/disk/cloud.go
> +			{Key: common.ClusterIDKey, Value: clusterID},
I think this will not work. It is selecting snapshots with both tags.

2024-08-02 10:29 UTC, huww98 commented on pkg/common/constants.go
> +	ClusterIDKey = "csi.storage.k8s.io/clusterid"
This should be added after line 46.
Maybe naming it `csi.alibabacloud.com/cluster-id` ? I think we should not use k8s.io without the consensus with the community.

2024-08-05 09:24 UTC, mowangdk commented
/

2024-08-05 09:24 UTC, closed without merging