metric: only enable when related driver is enabled
kubernetes-sigs/alibaba-cloud-csi-driver pull request #808
Opened 2023-07-31 09:00 UTC by huww98

#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:

we have multiple drivers and multiple metric collectors in one binary. Only enable metric collectors that are related to the currently enabled drivers.

#### Which issue(s) this PR fixes:

#### Special notes for your reviewer:

Once this or #807 is merged, I will edit the other one accordingly.

#### Does this PR introduce a user-facing change?

```release-note
CSI plugin now only export metrics about the enabled drivers
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

2023-08-01 04:01 UTC, huww98 commented
Since #807 is merged, I've updated this PR to also account for the `local_stats` collector

2023-08-01 12:29 UTC, mowangdk commented
/ok-to-test

2023-08-02 02:49 UTC, huww98 commented
Fixed a bug that cause drivers to bind to wrong csi socket address.

2023-08-02 07:33 UTC, huww98 commented
pfs_block_stat collector now goes with disk driver

2023-08-03 06:14 UTC, tydra-wang approved these changes

2023-08-03 08:03 UTC, mowangdk requested changes

2023-08-03 08:07 UTC, huww98 commented on pkg/metric/collector.go
> +		enabledDrivers := map[string]bool{}
OK, changed.

2023-08-03 08:11 UTC, mowangdk commented
/lgtm

2023-08-03 08:11 UTC, merged